version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      actions:
        patterns:
          - *
  - package-ecosystem: cargo
    directory: native/rust
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    groups:
      crates:
        patterns:
          - *
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
    groups:
      maven:
        patterns:
          - *
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
    groups:
      npm:
        patterns:
          - *
