version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: mix
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: elm
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: pub
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: swift
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: terraform
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
